<?php

namespace Database\Factories;

use App\Models\Project;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Project> */
final class ProjectFactory extends Factory
{
    protected $model = Project::class;

    /**
     * Project statuses.
     *
     * @var array<int, string>
     */
    private const STATUSES = [
        'active',
        'completed',
        'on_hold',
        'cancelled',
    ];

    /**
     * GBP Status values (syncs with Client).
     *
     * @var array<int, string>
     */
    private const GBP_STATUSES = [
        'not_created',
        'created',
        'pending',
        'verified',
        'suspended',
    ];

    public function definition(): array
    {
        // Generate realistic budget and price in cents
        // Budget: $500 to $10,000 (50000 to 1000000 cents)
        // Price: Usually budget * 1.2 to 2.0
        $budgetCents = $this->faker->numberBetween(50000, 1000000);
        $priceCents = (int) ($budgetCents * $this->faker->randomFloat(2, 1.2, 2.0));

        return [
            'organization_id' => 1,
            'client_id' => 1,
            'title' => $this->faker->sentence(4),
            'project_code' => null, // Should be generated by the application logic
            'description' => $this->faker->optional(0.7)->paragraph(),
            'status' => $this->faker->randomElement(self::STATUSES),
            'budget_cents' => $this->faker->optional(0.8)->passthrough($budgetCents),
            'price_cents' => $this->faker->optional(0.8)->passthrough($priceCents),
            'billable' => $this->faker->boolean(90), // 90% billable
            'gbp_status' => $this->faker->optional(0.6)->randomElement(self::GBP_STATUSES),
            'start_date' => $this->faker->optional(0.7)->dateTimeBetween('-6 months', 'now'),
            'end_date' => $this->faker->optional(0.4)->dateTimeBetween('now', '+6 months'),
            'notes_sales' => $this->faker->optional(0.3)->paragraph(),
            'notes_cst' => $this->faker->optional(0.5)->paragraph(),
            'notes_tech' => $this->faker->optional(0.4)->paragraph(),
            // Foreign keys (project_manager_id, department_id) 
            // should be set explicitly when creating with relationships
        ];
    }

    /**
     * State for an active project.
     */
    public function active(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'active',
            'billable' => true,
        ]);
    }

    /**
     * State for a completed project.
     */
    public function completed(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'completed',
            'end_date' => $this->faker->dateTimeBetween('-3 months', 'now'),
        ]);
    }
}
