name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Composer install
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Pint (formatter) – check mode
        run: vendor/bin/pint --test

      - name: PHPStan
        run: php -d xdebug.mode=off vendor/bin/phpstan analyse --memory-limit=1G

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: NPM ci
        run: npm ci

      - name: TS typecheck (if you added it)
        run: npm run typecheck || echo "typecheck script not present"

      - name: Build (Vite)
        env:
          VITE_PORT: 5199
        run: npm run build
